// Copyright (C) 2026 Zac Sweers
// SPDX-License-Identifier: Apache-2.0
package dev.zacsweers.moshix.ir.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.zacsweers.moshix.ir.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("moshi-ir/moshi-compiler-plugin/testData/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class MoshiDiagnosticTestGenerated extends AbstractMoshiDiagnosticTest {
  private void run(String fileName) {
    runTest("moshi-ir/moshi-compiler-plugin/testData/diagnostic/" + fileName);
  }

  @Test
  @TestMetadata("AbstractClassesNotSupported.kt")
  public void testAbstractClassesNotSupported() {
    run("AbstractClassesNotSupported.kt");
  }

  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("moshi-ir/moshi-compiler-plugin/testData/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("CorrectConstructorParam.kt")
  public void testCorrectConstructorParam() {
    run("CorrectConstructorParam.kt");
  }

  @Test
  @TestMetadata("DefaultObjectAndFallbackAdapter.kt")
  public void testDefaultObjectAndFallbackAdapter() {
    run("DefaultObjectAndFallbackAdapter.kt");
  }

  @Test
  @TestMetadata("EnumClassesNotSupported.kt")
  public void testEnumClassesNotSupported() {
    run("EnumClassesNotSupported.kt");
  }

  @Test
  @TestMetadata("ExtendJavaType.kt")
  public void testExtendJavaType() {
    run("ExtendJavaType.kt");
  }

  @Test
  @TestMetadata("ExtendPlatformType.kt")
  public void testExtendPlatformType() {
    run("ExtendPlatformType.kt");
  }

  @Test
  @TestMetadata("IgnoredConstructorDefaultsForUnitNothingAndVoid.kt")
  public void testIgnoredConstructorDefaultsForUnitNothingAndVoid() {
    run("IgnoredConstructorDefaultsForUnitNothingAndVoid.kt");
  }

  @Test
  @TestMetadata("InnerClassesNotSupported.kt")
  public void testInnerClassesNotSupported() {
    run("InnerClassesNotSupported.kt");
  }

  @Test
  @TestMetadata("InterfacesDoNotErrorWhenGeneratorNotSet.kt")
  public void testInterfacesDoNotErrorWhenGeneratorNotSet() {
    run("InterfacesDoNotErrorWhenGeneratorNotSet.kt");
  }

  @Test
  @TestMetadata("InterfacesNotSupported.kt")
  public void testInterfacesNotSupported() {
    run("InterfacesNotSupported.kt");
  }

  @Test
  @TestMetadata("InvalidConstructorParam.kt")
  public void testInvalidConstructorParam() {
    run("InvalidConstructorParam.kt");
  }

  @Test
  @TestMetadata("InvisibleFallbackAdapterConstructor.kt")
  public void testInvisibleFallbackAdapterConstructor() {
    run("InvisibleFallbackAdapterConstructor.kt");
  }

  @Test
  @TestMetadata("MultipleErrors.kt")
  public void testMultipleErrors() {
    run("MultipleErrors.kt");
  }

  @Test
  @TestMetadata("NestedSealedWithCommonSubtypes.kt")
  public void testNestedSealedWithCommonSubtypes() {
    run("NestedSealedWithCommonSubtypes.kt");
  }

  @Test
  @TestMetadata("NonFieldApplicableQualifier.kt")
  public void testNonFieldApplicableQualifier() {
    run("NonFieldApplicableQualifier.kt");
  }

  @Test
  @TestMetadata("NonPropertyConstructorParameter.kt")
  public void testNonPropertyConstructorParameter() {
    run("NonPropertyConstructorParameter.kt");
  }

  @Test
  @TestMetadata("NonRuntimeQualifier.kt")
  public void testNonRuntimeQualifier() {
    run("NonRuntimeQualifier.kt");
  }

  @Test
  @TestMetadata("NullAndDefaultObject.kt")
  public void testNullAndDefaultObject() {
    run("NullAndDefaultObject.kt");
  }

  @Test
  @TestMetadata("NullAndFallback.kt")
  public void testNullAndFallback() {
    run("NullAndFallback.kt");
  }

  @Test
  @TestMetadata("ObjectDeclarationsNotSupported.kt")
  public void testObjectDeclarationsNotSupported() {
    run("ObjectDeclarationsNotSupported.kt");
  }

  @Test
  @TestMetadata("PrivateClassesNotSupported.kt")
  public void testPrivateClassesNotSupported() {
    run("PrivateClassesNotSupported.kt");
  }

  @Test
  @TestMetadata("PrivateConstructor.kt")
  public void testPrivateConstructor() {
    run("PrivateConstructor.kt");
  }

  @Test
  @TestMetadata("PrivateConstructorParameter.kt")
  public void testPrivateConstructorParameter() {
    run("PrivateConstructorParameter.kt");
  }

  @Test
  @TestMetadata("PrivateProperties.kt")
  public void testPrivateProperties() {
    run("PrivateProperties.kt");
  }

  @Test
  @TestMetadata("RequiredIgnoredConstructorParameterFails.kt")
  public void testRequiredIgnoredConstructorParameterFails() {
    run("RequiredIgnoredConstructorParameterFails.kt");
  }

  @Test
  @TestMetadata("RequiredTransientConstructorParameterFails.kt")
  public void testRequiredTransientConstructorParameterFails() {
    run("RequiredTransientConstructorParameterFails.kt");
  }

  @Test
  @TestMetadata("SealedClassesNotSupported.kt")
  public void testSealedClassesNotSupported() {
    run("SealedClassesNotSupported.kt");
  }

  @Test
  @TestMetadata("TypeAliasesShareAdapter.kt")
  public void testTypeAliasesShareAdapter() {
    run("TypeAliasesShareAdapter.kt");
  }
}
